name: repull
description: Pull your release assets.
version: 1.0.0
repository: https://github.com/clragon/repull

environment:
  sdk: ^3.2.0

dependencies:
  deep_pick: ^1.0.0
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  path: ^1.8.3
  yaml: ^3.1.2
  yaml_writer: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
