name: release

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  app_name: repull

jobs:
  build:
    strategy:
      matrix:
        include:
          # - os: windows-latest
          #   platform: windows
          #   qemu_arch: ""
          - os: ubuntu-latest
            platform: linux-amd64
            qemu_arch: ""
          - os: ubuntu-latest
            platform: linux-arm64
            qemu_arch: aarch64

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set up dart SDK
        if: matrix.qemu_arch == ''
        uses: dart-lang/setup-dart@v1

      - name: get dependencies
        if: matrix.qemu_arch == ''
        run: dart pub get

      - name: build application
        if: matrix.qemu_arch == ''
        run: dart compile exe lib/main.dart -o ${{ env.app_name }}_${{ matrix.platform }}

      - name: set up QEMU
        if: matrix.qemu_arch != ''
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.qemu_arch }}

      - name: build application in docker
        if: matrix.qemu_arch != ''
        run: |
          docker run \
            --rm \
            --platform linux/${{ matrix.qemu_arch }} \
            -v "$(pwd)":/app \
            -w /app \
            dart:stable \
            /bin/bash -c "\
              dart pub get && \
              dart compile exe lib/main.dart -o ${{ env.app_name }}_${{ matrix.platform }}"

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.app_name }}_${{ matrix.platform }}
          path: ${{ env.app_name }}_${{ matrix.platform }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: get version
        run: echo "VERSION=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            ./artifacts/${{ env.app_name }}_*/${{ env.app_name }}_*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
